export const PROJECTS_DATA = [
  {
    id: 'alloys',
    name: 'Alloys',
    url: 'https://alloys.total-infotech.com/',
    description: 'Enterprise-level e-commerce platform with advanced search capabilities and optimized performance',
    coverImage: 'alloys.png',
    category: 'E-Commerce',
    technologies: [
      'React',
      'Next.js',
      'Typescript',
      'styled-components',
      'MUI',
      'Eslint',
      'Solr Rest Api',
      'Code reviewer',
    ],
  },
  {
    id: 'portfolio',
    name: 'Kaleem Ullah',
    url: 'https://polite-genie-672ad3.netlify.app/',
    description: 'Personal portfolio website showcasing my projects and skills with modern animations',
    coverImage: 'portfolio.png',
    category: 'Web Apps',
    technologies: [
      'React',
      'Next.js',
      'Typescript',
      'Tailwind Css',
      'React Framer',
    ],
  },
  {
    id: 'yoga',
    name: 'Yoga International',
    url: 'https://yogainternational.com/',
    coverImage: 'yoga.png',
    description: 'Leading online yoga platform with video streaming, course management, and subscription features',
    category: 'Web Apps',
    technologies: [
      'React',
      'Gatsby.js',
      'Typescript',
      'Apollo GraphQL',
      'Algolia',
      'Contentfull',
      'style-components',
      'MUI',
      'Knex',
      'PostgresSql',
      'Eslint',
      'Pre-commit hooks',
      'Code Reviewer',
    ],
  },
  {
    id: 'boundless',
    name: 'Boundless Maldives',
    url: 'https://www.boundlessmaldives.com/',
    description: 'Luxury travel website for Maldives resorts with immersive visuals and booking system',
    coverImage: 'boundless.png',
    category: 'Landing Pages',
    technologies: [
      'React',
      'Gatsby.js',
      'CSS',
      'Sanity.io',
      'Netlify',
      'style-components',
      'React-Slick',
    ],
  },
  {
    id: 'dr-elard',
    name: 'Dr Elard',
    description: 'Medical aesthetic clinic website with appointment booking and service showcase',
    url: 'https://medecine-esthetique-app.netlify.app/',
    coverImage: 'dr-elard.png',
    category: 'Landing Pages',
    technologies: [
      'React',
      'Next.js',
      'Tailwind Css',
      'Typescript',
      'React Framer',
      'Performance Optimization',
      'Page Speed',
      'Netlify',
    ],
  },
  {
    id: 'yard-map',
    name: 'Yard Map Interactive Google Map',
    description: 'Interactive map application for yard management with real-time tracking and analytics',
    url: 'https://medecine-esthetique-app.netlify.app/',
    coverImage: 'yard-map.png',
    category: 'Web Apps',
    technologies: [
      'React',
      'Google Map API',
      'MUI',
      'styled-components',
      'Typescript',
      'Firebase Hosting',
    ],
  },
  {
    id: 'total-tools-search',
    name: 'Total Tools Search Widget',
    description: 'Advanced search widget for e-commerce platform with faceted search and filters',
    url: 'https://www.totaltools.com.au/catalogsearch/result/?q=Tools',
    coverImage: 'totaltools.png',
    category: 'E-Commerce',
    technologies: ['React', 'Webpack', 'CSS', 'Unbxd Search Api'],
  },
]
