export const PROJECTS_DATA = [
  {
    id: 1,
    slug: 'alloys',
    name: 'Alloys',
    url: 'https://alloys.total-infotech.com/',
    demo: 'https://alloys.total-infotech.com/',
    description:
      'A comprehensive B2B e-commerce platform for alloy products with advanced search capabilities and real-time inventory management.',
    coverImage: '/alloys.png',
    thumbnail: '/alloys.png',
    category: 'E-commerce',
    duration: '4 months',
    team: '3 developers',
    role: 'Lead Frontend Developer',
    technologies: [
      'React',
      'Next.js',
      'Typescript',
      'styled-components',
      'MUI',
      'Eslint',
      'Solr Rest Api',
      'Code reviewer',
    ],
    features: [
      'Advanced product search with Solr',
      'Real-time inventory tracking',
      'B2B customer portal',
      'Custom pricing engine',
      'Responsive design',
      'Performance optimized',
    ],
  },
  {
    id: 2,
    slug: 'portfolio',
    name: 'Portfolio Website',
    url: 'https://polite-genie-672ad3.netlify.app/',
    demo: 'https://polite-genie-672ad3.netlify.app/',
    github: 'https://github.com/kaleemullahdev/portfolio',
    description:
      'Modern portfolio website with smooth animations and interactive components showcasing projects and skills.',
    coverImage: '/portfolio.png',
    thumbnail: '/portfolio.png',
    category: 'Portfolio',
    duration: '2 weeks',
    team: 'Solo Developer',
    role: 'Full Stack Developer',
    technologies: ['React', 'Next.js', 'Typescript', 'Tailwind Css', 'React Framer'],
    features: [
      'Smooth scroll animations',
      'Interactive project showcase',
      'Responsive design',
      'Dark mode support',
      'Contact form integration',
      'SEO optimized',
    ],
  },
  {
    id: 3,
    slug: 'yoga-international',
    name: 'Yoga International',
    url: 'https://yogainternational.com/',
    demo: 'https://yogainternational.com/',
    description:
      'Premium yoga education platform with thousands of classes, articles, and courses from world-renowned instructors.',
    coverImage: '/yoga.png',
    thumbnail: '/yoga.png',
    category: 'Education Platform',
    duration: '6 months',
    team: '5 developers',
    role: 'Senior Frontend Developer',
    technologies: [
      'React',
      'Gatsby.js',
      'Typescript',
      'Apollo GraphQL',
      'Algolia',
      'Contentfull',
      'style-components',
      'MUI',
      'Knex',
      'PostgresSql',
      'Eslint',
      'Pre-commit hooks',
      'Code Reviewer',
    ],
    features: [
      'Video streaming platform',
      'Advanced search with Algolia',
      'Subscription management',
      'Progress tracking',
      'Offline download capability',
      'Multi-device sync',
    ],
  },
  {
    id: 4,
    slug: 'boundless-maldives',
    name: 'Boundless Maldives',
    url: 'https://www.boundlessmaldives.com/',
    demo: 'https://www.boundlessmaldives.com/',
    description:
      'Luxury travel and tourism website showcasing premium resort experiences in the Maldives with immersive visuals.',
    coverImage: '/boundless.png',
    thumbnail: '/boundless.png',
    category: 'Travel & Tourism',
    duration: '6 weeks',
    team: '2 developers',
    role: 'Frontend Developer',
    technologies: [
      'React',
      'Gatsby.js',
      'CSS',
      'Sanity.io',
      'Netlify',
      'style-components',
      'React-Slick',
    ],
    features: [
      'Immersive image galleries',
      'CMS integration with Sanity',
      'Booking system integration',
      'Interactive resort maps',
      'Multi-language support',
      'Mobile optimized',
    ],
  },
  {
    id: 5,
    slug: 'dr-elard',
    name: 'Dr Elard Medical',
    description:
      'Modern medical practice website with appointment booking and patient portal for aesthetic medicine services.',
    url: 'https://medecine-esthetique-app.netlify.app/',
    demo: 'https://medecine-esthetique-app.netlify.app/',
    coverImage: '/dr-elard.png',
    thumbnail: '/dr-elard.png',
    category: 'Healthcare',
    duration: '8 weeks',
    team: 'Solo Developer',
    role: 'Full Stack Developer',
    technologies: [
      'React',
      'Next.js',
      'Tailwind Css',
      'Typescript',
      'React Framer',
      'Performance Optimization',
      'Page Speed',
      'Netlify',
    ],
    features: [
      'Online appointment booking',
      'Treatment catalog',
      'Before/after galleries',
      'Patient testimonials',
      'Contact forms',
      'Mobile responsive',
    ],
  },
  {
    id: 6,
    slug: 'yard-map',
    name: 'Yard Map Interactive',
    description:
      'Interactive mapping solution for yard management with real-time tracking and custom location markers.',
    url: 'https://yard-map-demo.web.app/',
    demo: 'https://yard-map-demo.web.app/',
    coverImage: '/yard-map.png',
    thumbnail: '/yard-map.png',
    category: 'Mapping Solution',
    duration: '3 weeks',
    team: 'Solo Developer',
    role: 'Frontend Developer',
    technologies: [
      'React',
      'Google Map API',
      'MUI',
      'styled-components',
      'Typescript',
      'Firebase Hosting',
    ],
    features: [
      'Interactive Google Maps integration',
      'Custom markers and overlays',
      'Real-time location tracking',
      'Route optimization',
      'Geofencing capabilities',
      'Mobile responsive',
    ],
  },
  {
    id: 7,
    slug: 'total-tools-search',
    name: 'Total Tools Search Widget',
    description:
      'Advanced search widget for e-commerce platform with auto-complete, filtering, and instant results.',
    url: 'https://www.totaltools.com.au/catalogsearch/result/?q=Tools',
    demo: 'https://www.totaltools.com.au/catalogsearch/result/?q=Tools',
    coverImage: '/totaltools.png',
    thumbnail: '/totaltools.png',
    category: 'Search Solution',
    duration: '4 weeks',
    team: '2 developers',
    role: 'Frontend Developer',
    technologies: ['React', 'Webpack', 'CSS', 'Unbxd Search Api'],
    features: [
      'Instant search results',
      'Auto-complete suggestions',
      'Advanced filtering options',
      'Search analytics',
      'Mobile optimized',
      'High performance',
    ],
  },
];
